var ipc__binary_8h =
[
    [ "di::execution::ipc_binary_ns::Client", "structdi_1_1execution_1_1ipc__binary__ns_1_1Client.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1Client" ],
    [ "di::execution::ipc_binary_ns::Server", "structdi_1_1execution_1_1ipc__binary__ns_1_1Server.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1Server" ],
    [ "di::execution::ipc_binary_ns::MessageHeader", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageHeader.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageHeader" ],
    [ "di::execution::ipc_binary_ns::ConnectionDataT< Proto, Read, Write, Alloc >", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionDataT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionDataT" ],
    [ "di::execution::ipc_binary_ns::ConnectionDataT< Proto, Read, Write, Alloc >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionDataT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionDataT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::MessageDecode< Proto, ClientOrServer >", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode" ],
    [ "di::execution::ipc_binary_ns::MessageDecode< Proto, ClientOrServer >::Sender", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender" ],
    [ "di::execution::ipc_binary_ns::MessageDecode< Proto, ClientOrServer >::Sender::OperationStateT< Rec >", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender_1_1OperationStateT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender_1_1OperationStateT" ],
    [ "di::execution::ipc_binary_ns::MessageDecode< Proto, ClientOrServer >::Sender::OperationStateT< Rec >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender_1_1OperationStateT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender_1_1OperationStateT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::MessageSequence< Proto, Read, Write, Alloc, ClientOrServer >", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageSequence.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageSequence" ],
    [ "di::execution::ipc_binary_ns::ConnectionTokenT< Proto, Read, Write, Alloc, ClientOrServer >", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionTokenT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionTokenT" ],
    [ "di::execution::ipc_binary_ns::ConnectionTokenT< Proto, Read, Write, Alloc, ClientOrServer >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionTokenT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionTokenT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::SequenceOpRecT< Op >", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceOpRecT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceOpRecT" ],
    [ "di::execution::ipc_binary_ns::SequenceOpRecT< Op >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceOpRecT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceOpRecT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::SequenceOpT< Proto, Read, Write, Fun, Alloc, ClientOrServer, Rec >", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceOpT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceOpT" ],
    [ "di::execution::ipc_binary_ns::SequenceOpT< Proto, Read, Write, Fun, Alloc, ClientOrServer, Rec >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceOpT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceOpT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::SequenceT< Proto, Read, Write, Fun, Alloc, ClientOrServer >", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceT" ],
    [ "di::execution::ipc_binary_ns::SequenceT< Proto, Read, Write, Fun, Alloc, ClientOrServer >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1SequenceT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::ConnectionT< Proto, Read, Write, Fun, Alloc, ClientOrServer >", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionT" ],
    [ "di::execution::ipc_binary_ns::ConnectionT< Proto, Read, Write, Fun, Alloc, ClientOrServer >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::ConnectToClientFunction< Proto >", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectToClientFunction.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectToClientFunction" ],
    [ "di::execution::ipc_binary_ns::ConnectToServerFunction< Proto >", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectToServerFunction.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectToServerFunction" ],
    [ "ClientConnection", "ipc__binary_8h.html#a43007e4d8ef4dd37c694dd763bbd5f55", null ],
    [ "ConnectionData", "ipc__binary_8h.html#aa0a71671b8164098e4bc3bf478ab627e", null ],
    [ "ConnectionToken", "ipc__binary_8h.html#a424645f17b1ac1d26dd8da55afd63647", null ],
    [ "Sequence", "ipc__binary_8h.html#acb77e07dd8b65815b3a80430d07a1e2a", null ],
    [ "SequenceOp", "ipc__binary_8h.html#adb75b6de08563994c64b1379107b6065", null ],
    [ "SequenceOpRec", "ipc__binary_8h.html#a3f5dc25722e4d0eba23aad778a8b284c", null ],
    [ "ServerConnection", "ipc__binary_8h.html#ad5e3f2532c2f2dec909e709a321662d5", null ],
    [ "ipc_binary_connect_to_client", "ipc__binary_8h.html#a386071398ec9c52071a0754c9ca33e5e", null ],
    [ "ipc_binary_connect_to_server", "ipc__binary_8h.html#a542a5d23d60497ba23476a1b8a9238fe", null ],
    [ "message_decode", "ipc__binary_8h.html#a9427c72672e3f39749dedc8255fcbafb", null ],
    [ "message_sequence", "ipc__binary_8h.html#a0ebb41803cfcc4559859c13c91c68d3d", null ]
];